- name: deploy base services
  hosts: target
  gather_facts: no
  become: yes
  become_user: "root"
  roles:
    - { role: bootstrap, tags: ['bootstrap']}
    - { role: networking, tags: ['networking']}
    - { role: docker, tags: ['docker']}

- name: deploy databases
  hosts: target
  gather_facts: no
  become: yes
  become_user: "root"
  roles:
    - { role: postgresql, tags: ['postgresql']}

- name: deploy fast-only databases
  hosts: fast
  gather_facts: no
  become: yes
  become_user: "root"
  roles:
    - { role: mysql, tags: ['mysql']}
    - { role: oracle, tags: ['oracle']}
    - { role: mssql, tags: ['mssql']}

- name: deploy jenkins, front-facing services
  hosts: target
  gather_facts: no
  become: yes
  become_user: "root"
  roles:
    - { role: jenkins, tags: ['jenkins']}
    - { role: scripts, tags: ['scripts']}  # scripts is dependent on jenkins
    # - { role: collectd, tags: ['collectd']}

